### ISSUE TITLE
Documentation on how setup a playbook to run the various modules

### ISSUE THREAD

**Issue by dimitrigraf** [dell/ansible-unity#10]
Hi there

I would like to use the Dell EMC Unity Ansible modules but have a rather hard time figuring out what the exact requirements are and what needs to be defined in the playbook in order to run the various modules.

Is there a documentation about that somewhere or some examples apart from the module ones?

Thanks in advance.

**Comment by rajendraindukuri** [comment]
Hi @dimitrigraf ,
Thanks for writing to us. This is all the documentation we have and samples provided in https://github.com/dell/ansible-unity/blob/1.2.1/docs/Product%20Guide.md for each module are very simple and self explanatory. Could you please be specific about the issue you are facing so that we can try help resolve your issues?

Thanks
Rajendra

**Comment by dimitrigraf** [comment]
Hi Rajendra

Well, what would a playbook look like that would run one of the modules in a task? Where is the playbook run? Locally?

For example, when using `dellemc.os10.os10_command` to get some information from an access switch, you have to set `connection: network_cli` and some additional variables like `ansible_become_method`

What is needed to use these unity modules? Which variables need to be set etc.

Kind regards
Dimitri

**Comment by dimitrigraf** [comment]
So, for anyone else stumbling upon this:

```
---  
- hosts: all
  collections:
  - dellemc.unity
     
  tasks:
  - name: example task
    dellemc.unity.dellemc_unity_filesystem:
      unispherehost: x.x.x.x
      username: user_name
      password: pass_word
      parameter1: value1
      paremter2: value2
    delegate_to: localhost  
```

Are these modules in an early stage of development? A few remarks:
- having to type username and password as clear text parameters is less than nice
- is there a way to set these first few parameters for connecting to Unity in a more secure and also less repetitive way?
